name: audioplayers_android
resolution: workspace
publish_to: none
description: Android implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 5.3.2
homepage: https://github.com/Sebastien-VZN/audioplayers
repository: https://github.com/Sebastien-VZN/audioplayers/tree/main/packages/audioplayers_android

flutter:
  plugin:
    implements: audioplayers
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin

dependencies:
  audioplayers_platform_interface:
    path: ../audioplayers_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'
