name: audioplayers
repository: https://github.com/bluefireteam/audioplayers

packages:
  - packages/**
  - examples/**
  - tutorials/**

command:
  bootstrap:
    # Avoid concurrent pub requests, remove when https://github.com/dart-lang/pub/issues/3404 is fixed
    runPubGetInParallel: false

scripts:
  lint:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: melos exec -c 10 flutter analyze
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  dartdoc:
    run: melos exec dart doc
    description: Run `dart doc` for all non-example packages.
    packageFilters:
      ignore: "*_example"

  pub-outdated:
    run: melos exec dart pub outdated
    description: Run `dart pub outdated` for all packages.

  pub-upgrade:
    # May fails until https://github.com/dart-lang/pub/pull/3920 is released
    run: melos exec dart pub upgrade --major-versions
    description: Run `dart pub upgrade --major-versions` for all packages.

  test:select:
    run: melos exec flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.
