name: audioplayers_workspace
repository: https://github.com/Sebastien-VZN/audioplayers
workspace:
  - packages/audioplayers
  - packages/audioplayers/example
  - packages/audioplayers/example/server
  - packages/audioplayers_android
  - packages/audioplayers_android_exo
  - packages/audioplayers_darwin
  - packages/audioplayers_linux
  - packages/audioplayers_platform_interface
  - packages/audioplayers_web
  - packages/audioplayers_windows

environment:
  sdk: ^3.6.0
