name: audioplayers_example
resolution: workspace
description: Demonstrates how to use the audioplayers plugin.
publish_to: none

dependencies:
  audioplayers:
    path: ../
  collection: ^1.19.1
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  http: ^1.3.1
  integration_test:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  # Integration tests for audioplayers_platform_interface are handled 
  # in this package to avoid maintaining multiple example apps:
  audioplayers_platform_interface:
    path: ../../audioplayers_platform_interface
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'
