name: build
on:
  push:

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    with:
      enable_android: false
      enable_web: false
      enable_ios: false
      enable_windows: true
      enable_linux: false
      enable_macos: false
