name: pull-request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
